name: pact
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # --- Core ---
  - python=3.12
  - pip
  - numpy
  - ffmpeg
  - pytorch-cuda=11.8


  # --- Pip installs everything else ---
  - pip:
      - -e .
      - torch==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - torchaudio==2.4.1+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - accelerate==1.1.1
      - bitsandbytes==0.44.1
      - datasets
      - evaluate
      - sentencepiece
      - fastapi
      - uvicorn
      - wandb
      - timm
      - opencv-python
      - decord
      - faiss-cpu
      - lxml
      - pandas
      - matplotlib
      - scikit-learn
      - numba
      - numexpr
      - sympy
      - python-dotenv
      - tqdm
      - regex
      - rich
      - seaborn
      - huggingface-hub
      - safetensors
      - jupyter
      - black
      - isort
      - mypy
      - pytest
      - loguru
      - sacrebleu
      - tokenizers==0.20
      - sqlitedict
      - tenacity
      - hf_transfer
      - av
      - einops
      - lmdb
      - pytablewriter
      - anthropic
      - async-timeout
      - cfgv
      - chardet
      - charset-normalizer
      - cloudpickle
      - cmake
      - dataproperty
      - diskcache
      - distlib
      - distro
      - dnspython
      - email-validator
      - et-xmlfile
      - exceptiongroup
      - fastapi-cli
      - ftfy
      - hf-transfer
      - httptools
      - httpx-sse
      - identify
      - importlib-metadata
      - interegular
      - jiter
      - jsonlines
      - lark
      - levenshtein
      - litellm
      - lm-format-enforcer
      - mbstrdecoder
      - ml-dtypes
      - msgpack
      - mutagen
      - ninja
      - nltk
      - nodeenv
      - onnx
      - onnxscript
      - openai
      - openpyxl
      - pathvalidate
      - pillow
      - pydantic-core
      - pytablewriter
      - qwen-vl-utils
      - rapidfuzz
      - reka-api
      - rouge
      - shellingham
      - tabledata
      - tcolorpy
      - tiktoken
      - typepy
      - typer
      - typing-extensions
      - uvloop
      - watchfiles
      - websockets
