name: pactenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=10.4.0
  - pip=25.0
  - pysocks=1.7.1
  - python=3.12.7
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.37.1
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - av==13.1.0
      - bitsandbytes==0.44.1
      - black==24.10.0
      - cfgv==3.4.0
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - cmake==3.30.5
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==3.0.2
      - decord==0.6.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - faiss-cpu==1.10.0
      - fastapi==0.115.3
      - fastapi-cli==0.0.5
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - hf-transfer==0.1.8
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.2
      - identify==2.6.1
      - importlib-metadata==8.5.0
      - interegular==0.3.3
      - isort==5.13.2
      - jiter==0.6.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lark==1.2.2
      - levenshtein==0.26.0
      - litellm==1.50.4
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.9
      - lmdb==1.6.2
      - loguru==0.7.2
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mutagen==1.47.0
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numba==0.60.0
      - numexpr==2.10.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.17.0
      - onnxscript==0.1.0.dev20241112
      - openai==1.52.2
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pathvalidate==3.2.1
      - platformdirs==4.3.6
      - portalocker==2.10.1
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - pyarrow==17.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.2
      - qwen-vl-utils==0.0.8
      - rapidfuzz==3.10.1
      - referencing==0.35.1
      - regex==2024.11.6
      - reka-api==3.2.0
      - rich==13.9.3
      - rouge==1.0.1
      - rpds-py==0.20.0
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - starlette==0.41.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.20.0
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - tqdm==4.67.1
      - triton==3.0.0
      - typepy==1.3.4
      - typer==0.15.2
      - tzdata==2025.2
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
      - -e .
